services:
  aztec-automator-service:
    platform: linux/amd64
    image: porcorossoj/aztec-automator-service:latest
    ports:
      - "3000:3000"
    environment:
      NODE_URL: https://a0a7-24-40-157-2.ngrok-free.app
    privileged: true
    restart: unless-stopped
